### ISSUE TITLE
[BUG]: ftmetric with NFiNext Stategy error

### ISSUE THREAD

**Issue by pcassimans** [kamontat/fthelper#20]
# Bug report

## Describe the bug
Get error in the log files when starting the ftmetric container

Application:
 - Version: [e.g. 4.5.3]

```Exception: input_arrays parameter missing required data key: close
20:56:55 freqtrade:connection:1A [WARN ] | Found error from freqtrade: Unexpected error input_arrays parameter missing required data key: close calling <bound method IStrategy._analyze_ticker_internal of <NostalgiaForInfinityNext.NostalgiaForInfinityNext object at 0x7f3adfdb4be0>>
Traceback (most recent call last):
  File "/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 17, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/freqtrade/strategy/interface.py", line 417, in _analyze_ticker_internal
    dataframe = self.analyze_ticker(dataframe, metadata)
  File "/freqtrade/freqtrade/strategy/interface.py", line 396, in analyze_ticker
    dataframe = self.advise_indicators(dataframe, metadata)
  File "/freqtrade/freqtrade/strategy/interface.py", line 761, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/freqtrade/user_data/strategies/NFiNext.py", line 2948, in populate_indicators
    informative_1h = self.informative_1h_indicators(dataframe, metadata)
  File "/freqtrade/user_data/strategies/NFiNext.py", line 2608, in informative_1h_indicators
    informative_1h['ema_12'] = ta.EMA(informative_1h, timeperiod=12)
  File "talib/_abstract.pxi", line 398, in talib._ta_lib.Function.__call__
  File "talib/_abstract.pxi", line 270, in talib._ta_lib.Function.set_function_args
  File "talib/_abstract.pxi", line 221, in talib._ta_lib.Function.set_input_arrays```

**Comment by kamontat** [comment]
This error is come from Freqtrade itself. Please either open on freqtrade repository or NFi repository.

By The Way, this error cause user confuse where the actual error is come from so I decide to remove this warning log from ftmetric. (Start from `v5.0.0-beta.3`)
