### ISSUE TITLE
Either i don't understand how it is supposed to work, or a simple one cluster env setup does not work:

### ISSUE THREAD

**Issue by kamontat** [kamontat/fthelper#29]
Either i don't understand how it is supposed to work, or a simple one cluster env setup does not work:

console args "--no-env-file --debug"

    environment:
      - FTH_CLUSTERS=1A
      - FTH_CLUSTER__1A__DB__ENABLED=false      
      - FTH_CLUSTER__1A__HTTP__ENABLED=true
      - FTH_CLUSTER__1A__HTTP__URL="http://freqtrade1:8081"
      - FTH_CLUSTER__1A__HTTP__APIVER=v1
      - FTH_CLUSTER__1A__HTTP__USERNAME="freqtrader"
      - FTH_CLUSTER__1A__HTTP__PASSWORD="secret"
      - FTH_SERVER__PORT=8091

09:11:28 command:default      [INFO ] | [with-cache] Connection cluster '1A'  http     - http://localhost:8080 ':'  database - localhost:5432 (postgres) ':'
09:11:28 client:http:1A       [DEBUG] | request: GET http://localhost:8080/api/v1/ping
09:11:28 cache:service        [DEBUG] | creating 'http.total-call.1A' data
09:11:28 client:http:1A       [DEBUG] | error: Get "http://localhost:8080/api/v1/ping": dial tcp 127.0.0.1:8080: connect: connection refused
09:11:28 cache:service        [DEBUG] | creating 'http.failure-call.1A' data panic: found '2' errors (2)
- Get "http://localhost:8080/api/v1/ping": dial tcp 127.0.0.1:8080: connect: connection refused
- failed to connect to `host=localhost user= database=freqtrade`: dial error (dial tcp [::1]:5432: connect: cannot assign requested address) goroutine 1 [running]: main.defaultCommand(0xc000077720, 0x203000, 0xc00006bb40) 	/home/runner/work/fthelper/fthelper/metric/main.go:55 +0x81a github.com/kamontat/fthelper/shared/commandline/commands.(*Command).Start(0xc00006afc0, 0xc000077720, 0x2, 0xc00006bb40) /home/runner/work/fthelper/fthelper/shared/commandline/commands/command.go:27 +0x5a github.com/kamontat/fthelper/shared/commandline.(*cli).Start(0xc00002fa80, 0xc00001e070, 0x7, 0x7, 0xc0001ba708, 0xc0001c83f0) /home/runner/work/fthelper/fthelper/shared/commandline/cli.go:87 +0x9b2 main.main() /home/runner/work/fthelper/fthelper/metric/main.go:97 +0x477

09:13:29 map:merger           [DEBUG] | merging key=log from <nil> -> map[level:4]
09:13:29 map:merger           [DEBUG] | merging key=fs from <nil> -> map[env:map[fullpath:[/fth/.env.docker] mode:multiple type:auto]]
09:13:29 map:merger           [DEBUG] | merging key=flag from <nil> -> map[noenv:true]
09:13:29 map:merger           [DEBUG] | merging key=variables from <nil> -> map[current:/fth]
09:13:29 map:merger           [DEBUG] | merging key=config from <nil> -> map[fullpath:[/fth/configs] mode:multiple type:auto]
09:13:29 map:merger           [DEBUG] | merging key=clusters from <nil> -> []
09:13:29 map:merger           [DEBUG] | merging key=level from 4 -> 2
09:13:29 map:merger           [DEBUG] | merging key=fs from <nil> -> {"config":{"fullpath":["/fth/configs"],"mode":"multiple","type":"auto"},"env":{"fullpath":["/fth/.env.docker"],"mode":"multiple","type":"auto"}}
09:13:29 map:merger           [DEBUG] | merging key=variables from <nil> -> {"current":"/fth"}
09:13:29 map:merger           [DEBUG] | merging key=clusters from <nil> -> []
09:13:29 map:merger           [DEBUG] | merging key=internal from <nil> -> map[flag:{"noenv":true} log:map[level:2] meta:{"buildby":"goreleaser","commit":"9a789b82aae38ffde2a14d38e7097ce22cb44499","date":"2021-08-24T15:03:23Z","name":"ftmetric","version":"5.0.0-beta.12"}]
09:13:29 config:builder       [DEBUG] | base configuration is {"clusters":[""],"fs":{"config":{"fullpath":["/fth/configs"],"mode":"multiple","type":"auto"},"env":{"fullpath":["/fth/.env.docker"],"mode":"multiple","type":"auto"}},"internal":{"flag":{"noenv":true},"log":{"level":2},"meta":{"buildby":"goreleaser","commit":"9a789b82aae38ffde2a14d38e7097ce22cb44499","date":"2021-08-24T15:03:23Z","name":"ftmetric","version":"5.0.0-beta.12"}},"variables":{"current":"/fth"}}
09:13:29 fs:type:resolver     [DEBUG] | mark /fth/configs as directory
09:13:29 config:builder       [DEBUG] | loading config from wrapper of 'multiple': [/fth/configs (directory)]
09:13:29 map:merger           [DEBUG] | merging key=server from <nil> -> map[metrics-path:/metrics port:8090]
09:13:29 map:merger           [DEBUG] | merging key=warmup from <nil> -> map[enabled:true interval:30s]
09:13:29 map:merger           [DEBUG] | merging key=clusters from <nil> -> []
09:13:29 map:merger           [DEBUG] | merging key=freqtrade from <nil> -> map[cache:map[balance:3m count:1m locks:5m logs:1m performance:1m ping:1s profit:5m schedule_perf:1m show_config:1m stats:5m version:10m whitelist:15m] db:map[enabled:true name:freqtrade password: type:postgres url:localhost:5432 username:] http:map[apiver:v1 enabled:true password: query:map[logs:map[limit:100]] url:http://localhost:8080 username:]]
09:13:29 config:builder       [DEBUG] | found some config in env
09:13:29 config:builder       [DEBUG] | override 'cluster.1a.db.enabled' from '<**** [<nil>] -> 'f**** [bool] (env)
09:13:29 config:builder       [DEBUG] | override 'cluster.1a.http.url' from '<**** [<nil>] -> '"http****************81" [string] (env)
09:13:29 config:builder       [DEBUG] | override 'server.port' from '8*** [float64] -> '8*** [float64] (env)
09:13:29 config:builder       [DEBUG] | override 'clusters' from '[* [[]interface {}] -> '[*** [[]interface {}] (env)
09:13:29 config:builder       [DEBUG] | override 'cluster.1a.http.apiver' from '<**** [<nil>] -> 'v* [string] (env)
09:13:29 config:builder       [DEBUG] | override 'cluster.1a.http.username' from '<**** [<nil>] -> '"fr********" [string] (env)
09:13:29 config:builder       [DEBUG] | override 'cluster.1a.http.password' from '<**** [<nil>] -> '"s*****" [string] (env)
09:13:29 config:builder       [DEBUG] | override 'cluster.1a.http.enabled' from '<**** [<nil>] -> 't*** [bool] (env)
panic: found '2' errors (2)
- Get "http://localhost:8080/api/v1/ping": dial tcp 127.0.0.1:8080: connect: connection refused
- failed to connect to `host=localhost user= database=freqtrade`: dial error (dial tcp [::1]:5432: connect: cannot assign requested address)
goroutine 1 [running]:
main.defaultCommand(0xc0000b6c80, 0x203000, 0xc0000b8e80)
	/home/runner/work/fthelper/fthelper/metric/main.go:55 +0x81a
github.com/kamontat/fthelper/shared/commandline/commands.(*Command).Start(0xc0000b8300, 0xc0000b6c80, 0x2, 0xc0000b8e80)
	/home/runner/work/fthelper/fthelper/shared/commandline/commands/command.go:27 +0x5a
github.com/kamontat/fthelper/shared/commandline.(*cli).Start(0xc0000b0500, 0xc00001e070, 0x7, 0x7, 0xc00009a3c8, 0xc0000ae730)
	/home/runner/work/fthelper/fthelper/shared/commandline/cli.go:87 +0x9b2
main.main()

_Originally posted by @loewensteinph in https://github.com/kamontat/fthelper/issues/23#issuecomment-922246556_

**Comment by kamontat** [comment]
For this one it's expected result. If ftmetric cannot connect to freqtrade it will panic exit.
This allow docker/systemctl to restart if something is wrong.

But I will make this config-able as disabled by default to not confuse new/old user too much.

**Comment by kamontat** [comment]
Sorry, fix on v5.0.0-beta.13 didn't make it proper fixed. 
I did fixed on `v5.0.0-beta.14` tested by myself.
